image: node:13.7.0

pages:
  cache:
    paths:
    - node_modules/

  script:
  - yarn install
  - yarn build
  - cp -r .vuepress/dist public

  artifacts:
    paths:
    - public
  
  only:
  - master

